default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  pool: 10
  timeout: 5000
  host: localhost
  port: 3306

development:
  <<: *default
  database: myproject
  username: root
  password: 

test:
  <<: *default
  database: myproject_test
  username: root
  password: 

production:
  <<: *default
  database: myproject
  username: 
  password: 